services:

  cab:
    build: 
      context: ./cab
    ports:
      - 8080:8080
    volumes:
      - ./cab/src/main/resources/test.txt:/test.txt


  rideservice:
    build:
      context: ./rideservice
    ports:
      - 8081:8080
    depends_on:
      - database



  wallet:
    build:
      context: ./wallet
    ports:
      - 8082:8080
    volumes:
      - ./wallet/src/main/resources/test.txt:/test.txt


  database:
    build: .
    ports:
      - 5432:5432