services:

  cab:
    image: mahabir10/cab
    ports:
      - 8080:8080
    volumes:
      - ./cab/src/main/resources/test.txt:/test.txt


  rideservice:
    image: mahabir10/rideservice
    ports:
      - 8081:8080
    depends_on:
      - database



  wallet:
    image: mahabir10/wallet
    ports:
      - 8082:8080
    volumes:
      - ./wallet/src/main/resources/test.txt:/test.txt


  database:
    image: mahabir10/database
    ports:
      - 5432:5432